name: Deploy to Lightsail

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Add SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.LIGHTSAIL_PRIVATE_KEY }}" > /htdocs/lightsail_ci_key
          chmod 400 /htdocs/lightsail_ci_key
          ssh-keyscan -H ${{ secrets.LIGHTSAIL_PUBLIC_IP }} >> ~/.ssh/known_hosts

      - name: Run deployment script
        run: |
          ssh -i /htdocs/lightsail_ci_key bitnami@${{ secrets.LIGHTSAIL_PUBLIC_IP }} << 'EOF'
            cd /htdocs
            git pull origin main
            # Restart service if needed
            # sudo systemctl restart your-app
          EOF

      - name: Clean up SSH key
        run: rm -rf ~/.ssh