name: Deploy to Lightsail

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4



      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.LIGHTSAIL_RESCUE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.LIGHTSAIL_HOST }} >> ~/.ssh/known_hosts

      - name: Run deployment script
        run: |
         ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa bitnami@${{ secrets.LIGHTSAIL_HOST }} << 'EOF'
          # Pull latest code to temp directory (replace with your repo path)
          cd /home/bitnami/htdocs || exit
          git pull origin main

          # Copy updated files to web root
          sudo cp -r /home/bitnami/htdocs/* /opt/bitnami/apache2/htdocs/

          # Fix ownership and permissions
          sudo chown -R bitnami:daemon /opt/bitnami/apache2/htdocs/
          sudo chmod -R 755 /opt/bitnami/apache2/htdocs/

          # Restart Apache (optional)
          sudo /opt/bitnami/ctlscript.sh restart apache
         EOF

      - name: Clean up SSH key
        run: rm -rf ~/.ssh